# k8s/aws-load-balancer-controller.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aws-load-balancer-controller
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://aws.github.io/eks-charts
    chart: aws-load-balancer-controller
    targetRevision: 1.8.1
    helm:
      parameters:
        - name: clusterName
          value: MY_CLUSTER            # ← your cluster name
        - name: serviceAccount.create
          value: "false"
        - name: serviceAccount.name
          value: aws-load-balancer-controller
        - name: region
          value: ap-south-1
        - name: vpcId
          value: MY_VPC_ID             # ← your VPC ID
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
