# k8s/hpa.yaml
# Auto-scales pods based on CPU usage
# Requires metrics-server: already included in EKS by default

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: car-backend-hpa
  namespace: autoelite
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: car-backend
  minReplicas: 2
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: car-frontend-hpa
  namespace: autoelite
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: car-frontend
  minReplicas: 2
  maxReplicas: 6
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
